{% set name = "probed" %}
{% set version = "0.0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/probed-{{ version }}.tar.gz
  sha256: ea5fff816cdc041314079724df34a3a666e11e04d899cf1a6a7a1c2f3aa16c40

build:
  number: 0
  noarch: python
  entry_points:
    - probed = probed.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - wheel
  run:
    - python >=3.6

test:
  imports:
    - probed
  commands:
    - pip check
    - probed --help
  requires:
    - pip

about:
  home: https://github.com/pyrustic/probed
  summary: Probed collections
  license: MIT
  license_file: LICENSE
  description: |
    Probed is a library that exposes three classes: ProbedDict,
     ProbedList and ProbedSet. These classes are containers like the
     built-in Python containers (dict, list, set) which they subclass
     with the added functionality in which the user is notified when the
     data content of collection changes, and the ability to put a probe
     into data collection to do more than just be notified.

extra:
  recipe-maintainers:
    - thewchan
